# Generated by Django 4.0.3 on 2022-03-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digikala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='product price', verbose_name='price'),
        ),
    ]
