# Generated by Django 4.0.3 on 2022-03-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digikala', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, help_text='product discription', null=True, verbose_name='discription'),
        ),
        migrations.AddField(
            model_name='product',
            name='gurantee',
            field=models.BooleanField(default=True, help_text='product gurantee check', verbose_name='gurantee'),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='product rate', null=True, verbose_name='rate'),
        ),
        migrations.AddField(
            model_name='product',
            name='saler',
            field=models.CharField(blank=True, help_text='product saler', max_length=255, null=True, verbose_name='saler'),
        ),
    ]
