# Generated by Django 4.0.3 on 2022-03-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digikala', '0003_product_discription_product_gurantee_product_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(blank=True, help_text='product rate', null=True, verbose_name='rate'),
        ),
    ]
